# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui1103.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(784, 582)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(784, 582))
        Form.setMaximumSize(QtCore.QSize(784, 582))
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 781, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(80, 41, 71, 16))
        self.label.setObjectName("label")
        self.btStart = QtWidgets.QPushButton(self.tab)
        self.btStart.setGeometry(QtCore.QRect(630, 16, 131, 20))
        self.btStart.setObjectName("btStart")
        self.lstInfo = QtWidgets.QListWidget(self.tab)
        self.lstInfo.setGeometry(QtCore.QRect(220, 70, 541, 451))
        self.lstInfo.setObjectName("lstInfo")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(220, 16, 54, 20))
        self.label_10.setObjectName("label_10")
        self.cbWorkMode = QtWidgets.QComboBox(self.tab)
        self.cbWorkMode.setGeometry(QtCore.QRect(280, 16, 111, 20))
        self.cbWorkMode.setObjectName("cbWorkMode")
        self.cbWorkMode.addItem("")
        self.cbWorkMode.addItem("")
        self.cbWorkMode.addItem("")
        self.cbLoop = QtWidgets.QCheckBox(self.tab)
        self.cbLoop.setGeometry(QtCore.QRect(570, 17, 51, 19))
        self.cbLoop.setObjectName("cbLoop")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(410, 16, 54, 20))
        self.label_11.setObjectName("label_11")
        self.cbLineMode = QtWidgets.QComboBox(self.tab)
        self.cbLineMode.setGeometry(QtCore.QRect(470, 16, 81, 20))
        self.cbLineMode.setObjectName("cbLineMode")
        self.cbLineMode.addItem("")
        self.cbLineMode.addItem("")
        self.cbLineMode.addItem("")
        self.txtServerIP = QtWidgets.QLineEdit(self.tab)
        self.txtServerIP.setGeometry(QtCore.QRect(280, 41, 111, 20))
        self.txtServerIP.setObjectName("txtServerIP")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(220, 40, 54, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(400, 40, 61, 20))
        self.label_14.setObjectName("label_14")
        self.txtServerPort = QtWidgets.QLineEdit(self.tab)
        self.txtServerPort.setGeometry(QtCore.QRect(470, 41, 81, 20))
        self.txtServerPort.setObjectName("txtServerPort")
        self.trChooseCase = QtWidgets.QTreeWidget(self.tab)
        self.trChooseCase.setGeometry(QtCore.QRect(30, 70, 171, 451))
        self.trChooseCase.setObjectName("trChooseCase")
        self.cbCross = QtWidgets.QCheckBox(self.tab)
        self.cbCross.setGeometry(QtCore.QRect(570, 40, 61, 19))
        self.cbCross.setWhatsThis("")
        self.cbCross.setObjectName("cbCross")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 761, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.txtCaseName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.txtCaseName.setObjectName("txtCaseName")
        self.horizontalLayout_2.addWidget(self.txtCaseName)
        self.btnSaveNewCase = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnSaveNewCase.setObjectName("btnSaveNewCase")
        self.horizontalLayout_2.addWidget(self.btnSaveNewCase)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 300, 761, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.trXX = QtWidgets.QTreeWidget(self.gridLayoutWidget)
        self.trXX.setObjectName("trXX")
        self.gridLayout.addWidget(self.trXX, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 761, 241))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.trSX = QtWidgets.QTreeWidget(self.gridLayoutWidget_2)
        self.trSX.setObjectName("trSX")
        self.gridLayout_2.addWidget(self.trSX, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 761, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.txtCarName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.txtCarName.setObjectName("txtCarName")
        self.horizontalLayout_3.addWidget(self.txtCarName)
        self.btSaveCar = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btSaveCar.setObjectName("btSaveCar")
        self.horizontalLayout_3.addWidget(self.btSaveCar)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 60, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 50, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 90, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(10, 140, 90, 21))
        self.label_7.setObjectName("label_7")
        self.txtLeftImage = QtWidgets.QLineEdit(self.tab_3)
        self.txtLeftImage.setGeometry(QtCore.QRect(110, 50, 581, 20))
        self.txtLeftImage.setObjectName("txtLeftImage")
        self.txtRightImage = QtWidgets.QLineEdit(self.tab_3)
        self.txtRightImage.setGeometry(QtCore.QRect(110, 80, 581, 20))
        self.txtRightImage.setObjectName("txtRightImage")
        self.txtLeftWheelImage = QtWidgets.QLineEdit(self.tab_3)
        self.txtLeftWheelImage.setGeometry(QtCore.QRect(110, 110, 581, 20))
        self.txtLeftWheelImage.setObjectName("txtLeftWheelImage")
        self.txtRightWheelImage = QtWidgets.QLineEdit(self.tab_3)
        self.txtRightWheelImage.setGeometry(QtCore.QRect(110, 140, 581, 20))
        self.txtRightWheelImage.setObjectName("txtRightWheelImage")
        self.txtCarKind = QtWidgets.QLineEdit(self.tab_3)
        self.txtCarKind.setGeometry(QtCore.QRect(110, 170, 581, 20))
        self.txtCarKind.setObjectName("txtCarKind")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(10, 170, 31, 21))
        self.label_8.setObjectName("label_8")
        self.txtCarLength = QtWidgets.QLineEdit(self.tab_3)
        self.txtCarLength.setGeometry(QtCore.QRect(110, 200, 581, 20))
        self.txtCarLength.setObjectName("txtCarLength")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(10, 200, 31, 21))
        self.label_9.setObjectName("label_9")
        self.toolButton = QtWidgets.QToolButton(self.tab_3)
        self.toolButton.setGeometry(QtCore.QRect(700, 51, 37, 18))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_2.setGeometry(QtCore.QRect(700, 80, 37, 18))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_3.setGeometry(QtCore.QRect(700, 110, 37, 18))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.tab_3)
        self.toolButton_4.setGeometry(QtCore.QRect(700, 140, 37, 18))
        self.toolButton_4.setObjectName("toolButton_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(90, 24, 54, 12))
        self.label_2.setObjectName("label_2")
        self.txtSXIP = QtWidgets.QLineEdit(self.tab_4)
        self.txtSXIP.setGeometry(QtCore.QRect(160, 20, 113, 20))
        self.txtSXIP.setObjectName("txtSXIP")
        self.txtXXIP = QtWidgets.QLineEdit(self.tab_4)
        self.txtXXIP.setGeometry(QtCore.QRect(160, 50, 113, 20))
        self.txtXXIP.setObjectName("txtXXIP")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(90, 54, 54, 12))
        self.label_15.setObjectName("label_15")
        self.txtSXWheelIP = QtWidgets.QLineEdit(self.tab_4)
        self.txtSXWheelIP.setGeometry(QtCore.QRect(160, 80, 113, 20))
        self.txtSXWheelIP.setObjectName("txtSXWheelIP")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(54, 80, 71, 20))
        self.label_16.setObjectName("label_16")
        self.txtXXWheelIP = QtWidgets.QLineEdit(self.tab_4)
        self.txtXXWheelIP.setGeometry(QtCore.QRect(160, 110, 113, 20))
        self.txtXXWheelIP.setObjectName("txtXXWheelIP")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(54, 111, 81, 16))
        self.label_17.setObjectName("label_17")
        self.txtImageTransportIP = QtWidgets.QLineEdit(self.tab_4)
        self.txtImageTransportIP.setGeometry(QtCore.QRect(160, 140, 113, 20))
        self.txtImageTransportIP.setObjectName("txtImageTransportIP")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(65, 142, 71, 16))
        self.label_18.setObjectName("label_18")
        self.txtImageTransportPort = QtWidgets.QLineEdit(self.tab_4)
        self.txtImageTransportPort.setGeometry(QtCore.QRect(160, 172, 113, 20))
        self.txtImageTransportPort.setObjectName("txtImageTransportPort")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(54, 174, 71, 16))
        self.label_19.setObjectName("label_19")
        self.txtFreeTime = QtWidgets.QLineEdit(self.tab_4)
        self.txtFreeTime.setGeometry(QtCore.QRect(160, 205, 113, 20))
        self.txtFreeTime.setObjectName("txtFreeTime")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(77, 207, 51, 16))
        self.label_20.setObjectName("label_20")
        self.btSaveSetting = QtWidgets.QPushButton(self.tab_4)
        self.btSaveSetting.setGeometry(QtCore.QRect(690, 20, 75, 23))
        self.btSaveSetting.setObjectName("btSaveSetting")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "自动化测试平台"))
        self.label.setText(_translate("Form", "执行场景列表"))
        self.btStart.setText(_translate("Form", "开始"))
        self.label_10.setText(_translate("Form", "工作模式"))
        self.cbWorkMode.setItemText(0, _translate("Form", "服务器和客户端"))
        self.cbWorkMode.setItemText(1, _translate("Form", "服务器"))
        self.cbWorkMode.setItemText(2, _translate("Form", "客户端"))
        self.cbLoop.setText(_translate("Form", "循环"))
        self.label_11.setText(_translate("Form", "线路模式"))
        self.cbLineMode.setItemText(0, _translate("Form", "单线单向"))
        self.cbLineMode.setItemText(1, _translate("Form", "单线双向"))
        self.cbLineMode.setItemText(2, _translate("Form", "双线单向"))
        self.label_13.setText(_translate("Form", "服务器IP"))
        self.label_14.setText(_translate("Form", "服务器端口"))
        self.trChooseCase.headerItem().setText(0, _translate("Form", "场景名称"))
        self.cbCross.setToolTip(_translate("Form", "勾选将加入交错车逻辑判断"))
        self.cbCross.setText(_translate("Form", "交错车"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "选择场景"))
        self.label_12.setText(_translate("Form", "场景标识"))
        self.btnSaveNewCase.setText(_translate("Form", "保存"))
        self.trXX.headerItem().setText(0, _translate("Form", "下行"))
        self.trXX.headerItem().setText(1, _translate("Form", "速度"))
        self.trXX.headerItem().setText(2, _translate("Form", "编码"))
        self.trXX.headerItem().setText(3, _translate("Form", "来车方向"))
        self.trXX.headerItem().setText(4, _translate("Form", "图片优先"))
        self.trXX.headerItem().setText(5, _translate("Form", "车厢标识"))
        self.trXX.headerItem().setText(6, _translate("Form", "车头标识"))
        self.trXX.headerItem().setText(7, _translate("Form", "车尾标识"))
        self.trSX.headerItem().setText(0, _translate("Form", "上行"))
        self.trSX.headerItem().setText(1, _translate("Form", "速度"))
        self.trSX.headerItem().setText(2, _translate("Form", "编码"))
        self.trSX.headerItem().setText(3, _translate("Form", "来车方向"))
        self.trSX.headerItem().setText(4, _translate("Form", "图片优先"))
        self.trSX.headerItem().setText(5, _translate("Form", "车厢标识"))
        self.trSX.headerItem().setText(6, _translate("Form", "车头标识"))
        self.trSX.headerItem().setText(7, _translate("Form", "车尾标识"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "新建场景"))
        self.label_3.setText(_translate("Form", "车厢标识"))
        self.btSaveCar.setText(_translate("Form", "保存"))
        self.label_4.setText(_translate("Form", "左侧图像"))
        self.label_5.setText(_translate("Form", "右侧图像"))
        self.label_6.setText(_translate("Form", "左侧走行部图像"))
        self.label_7.setText(_translate("Form", "右侧走行部图像"))
        self.label_8.setText(_translate("Form", "车型"))
        self.label_9.setText(_translate("Form", "车长"))
        self.toolButton.setText(_translate("Form", "..."))
        self.toolButton_2.setText(_translate("Form", "..."))
        self.toolButton_3.setText(_translate("Form", "..."))
        self.toolButton_4.setText(_translate("Form", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "新建车厢"))
        self.label_2.setText(_translate("Form", "上行IP"))
        self.label_15.setText(_translate("Form", "下行IP"))
        self.label_16.setText(_translate("Form", "上行走行部IP"))
        self.label_17.setText(_translate("Form", "下行走行部IP"))
        self.label_18.setText(_translate("Form", "传图服务IP"))
        self.label_19.setText(_translate("Form", "传图服务端口"))
        self.label_20.setText(_translate("Form", "空闲间隔"))
        self.btSaveSetting.setText(_translate("Form", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "首选项"))

